site_name: 教程
docs_dir: "mkdocs"
repo_url: https://github.com/idcos/cloudiac-docs
repo_name: cloudiac-docs
edit_uri: edit/master/tutorials/mkdocs/
theme:
  language: zh
  name: material
  logo: assets/svg/icon.svg
  favicon: assets/svg/icon.svg
  palette:
    primary: deep purple
  icon:
    repo: fontawesome/brands/github
plugins:
  - search:
      lang:
        - en
        - ja
      separator: '[\s\-\.]+' # 分词分隔符
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - "assets/css/custom.css"
  - "assets/css/simpleLightbox.min.css"
extra_javascript:
  - "assets/js/jquery.min.js"
  - "assets/js/simpleLightbox.min.js"
  - "assets/js/custom.js"
markdown_extensions:
  - markdown.extensions.attr_list
  - meta
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - footnotes
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid"

nav:
  - "快速入门":
      - "创建组织和项目": quick-start/create-org-project.md
      - "创建云模板": quick-start/create-template.md
      - "部署环境": quick-start/deploy-env.md

  - "Registry":
    - "Provider 发布": "cases/provider-publish.md"
    - "Module 发布": "cases/module-publish.md"
    - "策略组发布": "cases/policy-group-publish.md"
    - "获取签名密钥": cases/create-gpg-key.md
    - "添加签名密钥": cases/add-gpg-key.md
    - "vcs集成": cases/create-vcs.md
    - "token获取": cases/token.md

  - "典型场景":
    - "创建 aliyun ecs": "cases/aliyun-ecs.md"
    - "本地资源创建": "cases/all-in-one-example.md"
    - "资源变更检测": "cases/drift_detection.md"
    - "添加SSH密钥": "cases/ssh_key.md"
    - "一键部署": "cases/shell-deployment.md"
    - "云模板terraform版本选择": "cases/cloud_template.md"
    - "创建策略组": "cases/create-policy-group.md"
    - "为云模板开启合规策略": "cases/template-enable-policy.md"
    - "为环境开启合规策略": "cases/env-enable-policy.md"
    - "环境创建成功后定时销毁": "cases/env-auto-destroy.md"
    - "添加部署失败通知": "cases/deploy-failed-notification.md"
    - "使用 Registry 的 Provider": "cases/use-provider.md"
    - "使用合规策略限制测试环境的机器规格": "cases/opa-instance-type.md"
    - "环境创建成功后定时销毁": "cases/env-auto-destroy.md"
    - "使用 Registry 中的策略组": "cases/registry-policygroup.md"

  #  - "创建 aliyun ecs": "cases/aliyun-ecs.md"
  #  - "环境完整创建过程": "cases/all-in-one-example.md"
  #  - "使用漂移检测": ""
  #      演示各种通知渠道的配置方法，如何获取 token，url 如何填写
    - "通过 tfvars 文件预定义变量": "cases/tfvars.md"
      # 定义 dev.tfvars 和 prod.tfvars，分别用于开发环境和生成环境部署，其中使用的 vpc、实例规格等都不同
  #  - "使用 Pipeline 安装 ansible 依赖": |
  #      演示用户的 ansible playbook 中要使用指定的 collection，需要在执行 play 步骤前进行安装
  #      ansible collection 文档：https://docs.ansible.com/ansible/latest/user_guide/collections_using.html
  #  - "添加 SSH 密钥": |
  #      密钥如何生成，如何添加到平台，如何在云模板中将公钥绑定到创建的资源(演示 aliyun ecs)
  #  - "在云模板中指定 terraform 版本": ""
  #  - "接入 LDAP 认证": ""
  #  - "创建 ansible host group": |
  #      创建 ansible host group，并给主机组添加变量，然后演示在 playbook 中使用主机组及其变量
  #  - "通过环境变量开启 terraform 和 ansible 日志": "TF_LOG=debug, ANSIBLE_VERBOSITY=2"
  #  - "自定义 runner 镜像": ""
